# Generated by Django 2.1.14 on 2020-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='姓名')),
                ('gender', models.CharField(choices=[(0, 'null'), (1, '男'), (2, '女')], default=0, max_length=255, verbose_name='性别')),
            ],
        ),
    ]
